// MEGGA X — design system (transcription fidèle la vitrine MEGGA). Barrel d'export.
export { default as MeggaX } from './MeggaX'
export { default as MxButton } from './MxButton'
export { default as MxBadge } from './MxBadge'
export { default as MxInput } from './MxInput'
export { default as MxField } from './MxField'
export { default as MxModal } from './MxModal'
export { default as MxIcon } from './MxIcon'
export { default as MxLink } from './MxLink'
export { default as MxList } from './MxList'
export { default as MxStateMessage } from './MxStateMessage'
export { default as MxCheckbox } from './MxCheckbox'
export { default as MxRadio } from './MxRadio'
export { default as MxToggle } from './MxToggle'
export { default as MxSelect } from './MxSelect'
export { default as MxDatePicker, type MxDatePickerLabels } from './MxDatePicker'
export { default as MxAddressAutocomplete, type MxAddressLabels } from './MxAddressAutocomplete'
export { default as MxCompanySearch, type MxCompanyLabels } from './MxCompanySearch'
export { default as MxSuggestField, type MxSuggestItem, type MxSuggestLabels } from './MxSuggestField'
export { default as MxFrenchAddressField } from './MxFrenchAddressField'
export { default as MxFrenchCompanyField, type MxFrenchCompanyLabels } from './MxFrenchCompanyField'
export { default as MxAvatar } from './MxAvatar'
export { MX_ICONS, type MxIconSet } from './iconGlyphs'
