// GÉNÉRÉ par scripts/check-edge-roster.mjs — ne pas éditer à la main.
// Source de vérité : les dossiers de supabase/functions/ (hors _shared).
// Régénérer : node scripts/check-edge-roster.mjs --write (la CI bloque la dérive).
//
// NB : `sync-service-key` (déployée hors source-tree, volontairement — cf.
// mémoire service-key) n'apparaît pas ici : le roster reflète le REPO, pas le
// dashboard. Les fonctions retirées du repo mais encore déployées (zombies à
// supprimer au dashboard) n'y figurent pas non plus.

export const EDGE_FUNCTION_ROSTER = [
  'accept-team-invite',
  'admin-agency-lifecycle',
  'admin-dsar-export',
  'admin-monitoring',
  'admin-stripe-agency-billing',
  'admin-stripe-metrics',
  'admin-user-lifecycle',
  'agency-verification-notify',
  'agency-verification-run',
  'ai-billing-monitor',
  'ai-copilot',
  'appointment-book',
  'appointment-manage',
  'appointment-slots',
  'audit-pdf-export',
  'automation-engine',
  'backfill-cf-images',
  'buyer-reception-create',
  'buyer-reception-get',
  'buyer-reception-react',
  'c2pa-sign',
  'c2pa-verify',
  'delete-account',
  'detect-new-device',
  'email-unsubscribe',
  'esign-webhook',
  'extract-lead',
  'extract-property-pdf',
  'extract-property-url',
  'flatfox-sync',
  'google-calendar-sync',
  'idx-feed',
  'idx-syndicate',
  'intercom-identity',
  'kyb-identity-purge',
  'kyb-identity-read',
  'kyb-identity-verify',
  'kyc-report-data',
  'kyc-report-import',
  'kyc-report-pdf',
  'kyc-screening',
  'learn-agent-style',
  'log-auth-event',
  'magic-link-confirm',
  'magic-link-create',
  'magic-link-get',
  'magic-link-send-email',
  'magic-link-upload',
  'mail-actions',
  'mail-oauth',
  'mail-sync',
  'market-scraper',
  'matching-engine',
  'onboarding-call-book',
  'onboarding-call-manage',
  'onboarding-call-reminder',
  'onboarding-slots',
  'outlook-calendar-sync',
  'photo-processor',
  'property-photo-r2',
  'realadvisor-sync',
  'resend-webhook',
  'revoke-device-session',
  'send-email',
  'send-property-email',
  'send-relance-email',
  'send-reminder-email',
  'send-team-invite',
  'send-visit-email',
  'sign-document',
  'speech-to-text',
  'stripe-checkout',
  'stripe-portal',
  'stripe-webhook',
  'translate-on-demand',
  'virtual-staging',
  'weekly-digest',
  'weekly-report',
  'whatsapp-agent',
  'whatsapp-agent-async',
  'whatsapp-morning-brief',
  'whatsapp-optin-invite',
  'whatsapp-process',
  'whatsapp-verify-number',
  'whatsapp-webhook',
] as const
