export interface MockListing {
  id: string
  title: string
  price: number
  charges_monthly: number
  address: string
  city: string
  canton: string
  postal_code: string
  rooms: number
  bedrooms: number
  bathrooms: number
  surface_m2: number
  floor: number | null
  total_floors: number | null
  year_built: number
  photos: string[]
  is_hot?: boolean
  is_new?: boolean
  is_exclusive?: boolean
  type: 'apartment' | 'house' | 'villa' | 'commercial' | 'land'
  status: 'active' | 'reserved' | 'sold'
  description: string
  features: Record<string, string>
  lat: number
  lng: number
  agent: {
    name: string
    agency: string
    phone: string
    email: string
    photo: string
  }
}

export const MOCK_LISTINGS: MockListing[] = [
  {
    id: '1',
    title: 'Appartement lumineux aux Eaux-Vives',
    price: 720000,
    charges_monthly: 350,
    address: 'Rue du Lac 12',
    city: 'Genève',
    canton: 'GE',
    postal_code: '1207',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 1,
    surface_m2: 95,
    floor: 3,
    total_floors: 5,
    year_built: 2018,
    type: 'apartment',
    status: 'active',
    is_hot: true,
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&h=600&fit=crop',
    ],
    description: `Magnifique appartement de 4 pièces entièrement rénové, situé au cœur du quartier des Eaux-Vives à Genève. L'appartement bénéficie d'une luminosité exceptionnelle grâce à ses grandes baies vitrées orientées sud-ouest, offrant une vue dégagée sur le lac Léman.\n\nLe séjour spacieux de 35 m² s'ouvre sur un balcon de 8 m², idéal pour profiter des soirées d'été. La cuisine équipée haut de gamme (Siemens) est ouverte sur le salon. Les deux chambres sont de belles dimensions avec parquet en chêne massif.\n\nL'immeuble dispose d'un ascenseur, d'une buanderie commune et d'un local à vélos. Une place de parking souterrain est incluse dans le prix. Proximité immédiate des transports publics, commerces et écoles.`,
    features: {
      'Année de construction': '2018',
      'Chauffage': 'Sol, pompe à chaleur',
      'Parking': '1 place souterraine incluse',
      'Cave': 'Oui',
      'Balcon': '8 m², orienté sud-ouest',
      'Vue': 'Lac Léman',
      'Ascenseur': 'Oui',
      'État': 'Rénové en 2023',
    },
    lat: 46.2044,
    lng: 6.1621,
    agent: {
      name: 'Gregory Lyonnet',
      agency: 'MEGGA Immobilier',
      phone: '+41 22 700 12 34',
      email: 'gregory@megga.ch',
      photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    },
  },
  {
    id: '2',
    title: 'Duplex moderne à Champel',
    price: 1250000,
    charges_monthly: 520,
    address: 'Avenue de Champel 45',
    city: 'Genève',
    canton: 'GE',
    postal_code: '1206',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    surface_m2: 140,
    floor: 4,
    total_floors: 5,
    year_built: 2020,
    type: 'apartment',
    status: 'active',
    is_exclusive: true,
    photos: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop',
    ],
    description: `Superbe duplex de 5 pièces en attique avec vue panoramique sur le Salève et les Alpes. Cet appartement d'exception combine modernité et élégance dans l'un des quartiers les plus prisés de Genève.\n\nLe niveau inférieur comprend un vaste séjour-salon avec cheminée, une cuisine ouverte design, un WC visiteurs et un accès direct à la terrasse de 25 m². Le niveau supérieur abrite trois chambres dont une suite parentale avec dressing et salle de bains privative.\n\nFinitions haut de gamme : parquet chevron, domotique, stores électriques, triple vitrage. Deux places de parking souterrain et une cave. Résidence sécurisée avec conciergerie.`,
    features: {
      'Année de construction': '2020',
      'Chauffage': 'Sol, géothermie',
      'Parking': '2 places souterraines',
      'Cave': 'Oui, 8 m²',
      'Terrasse': '25 m², vue Alpes',
      'Vue': 'Salève, Alpes',
      'Ascenseur': 'Oui, privé',
      'État': 'Neuf',
    },
    lat: 46.1940,
    lng: 6.1540,
    agent: {
      name: 'Gregory Lyonnet',
      agency: 'MEGGA Immobilier',
      phone: '+41 22 700 12 34',
      email: 'gregory@megga.ch',
      photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    },
  },
  {
    id: '3',
    title: 'Studio rénové à Plainpalais',
    price: 385000,
    charges_monthly: 180,
    address: 'Rue de Carouge 78',
    city: 'Genève',
    canton: 'GE',
    postal_code: '1205',
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    surface_m2: 42,
    floor: 2,
    total_floors: 4,
    year_built: 1965,
    type: 'apartment',
    status: 'active',
    is_new: true,
    photos: [
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=800&h=600&fit=crop',
    ],
    description: `Charmant studio entièrement rénové au cœur de Plainpalais, à deux pas du parc des Bastions et de l'Université. Idéal pour un premier achat ou un investissement locatif avec un excellent rendement.\n\nL'espace a été intelligemment optimisé : coin nuit séparé par une verrière, cuisine américaine équipée, salle de douche moderne. Les finitions sont soignées : parquet clair, peinture fraîche, luminaires design.\n\nSituation idéale pour les transports (tram 12 et 18 à 50m), les commerces de la rue de Carouge et la vie culturelle du quartier.`,
    features: {
      'Année de construction': '1965, rénové 2024',
      'Chauffage': 'Radiateurs, gaz',
      'Parking': 'Non inclus',
      'Cave': 'Oui',
      'Balcon': 'Non',
      'Vue': 'Cour intérieure calme',
      'Ascenseur': 'Non',
      'État': 'Entièrement rénové',
    },
    lat: 46.1980,
    lng: 6.1400,
    agent: {
      name: 'Sophie Martin',
      agency: 'MEGGA Immobilier',
      phone: '+41 22 700 56 78',
      email: 'sophie@megga.ch',
      photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face',
    },
  },
  {
    id: '4',
    title: 'Villa avec vue sur le lac',
    price: 2950000,
    charges_monthly: 0,
    address: 'Chemin des Crêts 5',
    city: 'Cologny',
    canton: 'GE',
    postal_code: '1223',
    rooms: 7,
    bedrooms: 4,
    bathrooms: 3,
    surface_m2: 280,
    floor: null,
    total_floors: null,
    year_built: 2015,
    type: 'villa',
    status: 'active',
    is_hot: true,
    photos: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop',
    ],
    description: `Villa d'architecte exceptionnelle nichée sur les hauteurs de Cologny, offrant une vue imprenable à 180° sur le lac Léman et le jet d'eau. Cette propriété de standing allie design contemporain et matériaux nobles.\n\nLe rez-de-chaussée s'articule autour d'un grand séjour de 60 m² avec baies vitrées du sol au plafond, ouvrant sur une terrasse avec piscine chauffée. La cuisine professionnelle (La Cornue) jouxte une salle à manger formelle. À l'étage, la suite parentale offre un dressing de 12 m² et une salle de bains en marbre de Carrare.\n\nJardin paysager de 800 m², garage double, cave à vin climatisée, local technique. Système de sécurité, domotique complète. Quartier résidentiel calme, à 5 min de la vieille ville.`,
    features: {
      'Année de construction': '2015',
      'Chauffage': 'Sol, géothermie',
      'Parking': 'Garage double',
      'Cave': 'Cave à vin climatisée',
      'Piscine': 'Chauffée, extérieure',
      'Terrain': '800 m²',
      'Vue': 'Lac Léman, jet d\'eau, panoramique',
      'État': 'Excellent',
    },
    lat: 46.2180,
    lng: 6.1800,
    agent: {
      name: 'Gregory Lyonnet',
      agency: 'MEGGA Immobilier',
      phone: '+41 22 700 12 34',
      email: 'gregory@megga.ch',
      photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    },
  },
  {
    id: '5',
    title: 'Loft industriel aux Pâquis',
    price: 890000,
    charges_monthly: 400,
    address: 'Rue de Berne 22',
    city: 'Genève',
    canton: 'GE',
    postal_code: '1201',
    rooms: 3,
    bedrooms: 1,
    bathrooms: 1,
    surface_m2: 110,
    floor: 4,
    total_floors: 4,
    year_built: 1920,
    type: 'apartment',
    status: 'active',
    photos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&h=600&fit=crop',
    ],
    description: `Loft atypique de caractère dans un ancien bâtiment industriel reconverti. Hauts plafonds de 4m, poutres métalliques apparentes, grandes fenêtres industrielles — un espace unique aux Pâquis.\n\nL'espace ouvert de 110 m² comprend un séjour cathédrale, une mezzanine aménagée en chambre, une cuisine design en béton ciré et une salle de bains contemporaine. Le cachet industriel est préservé : murs en briques, sol en béton poli, tuyauteries apparentes.\n\nEn plein cœur du quartier des Pâquis, à proximité de la gare Cornavin, du lac et de tous les commerces. Idéal pour un profil créatif ou un couple.`,
    features: {
      'Année de construction': '1920, reconverti 2019',
      'Chauffage': 'Radiateurs, gaz de ville',
      'Parking': 'Non (places à louer à proximité)',
      'Cave': 'Oui',
      'Hauteur plafond': '4 mètres',
      'Vue': 'Toits de Genève',
      'Ascenseur': 'Oui (monte-charge reconverti)',
      'État': 'Rénové, caractère préservé',
    },
    lat: 46.2100,
    lng: 6.1450,
    agent: {
      name: 'Sophie Martin',
      agency: 'MEGGA Immobilier',
      phone: '+41 22 700 56 78',
      email: 'sophie@megga.ch',
      photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face',
    },
  },
  {
    id: '6',
    title: 'Appartement familial à Carouge',
    price: 650000,
    charges_monthly: 320,
    address: 'Place du Marché 8',
    city: 'Carouge',
    canton: 'GE',
    postal_code: '1227',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 1,
    surface_m2: 88,
    floor: 1,
    total_floors: 3,
    year_built: 1985,
    type: 'apartment',
    status: 'active',
    photos: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&h=600&fit=crop',
    ],
    description: `Bel appartement familial de 4 pièces idéalement situé sur la Place du Marché de Carouge, au cœur de la vie de quartier. Le charme de Carouge avec ses ruelles piétonnes, ses boutiques et restaurants, à votre porte.\n\nL'appartement offre un séjour traversant lumineux, une cuisine séparée récemment refaite, deux chambres spacieuses et une salle de bains avec baignoire. Un balcon couvert donne sur la place et son marché animé.\n\nEmplacement exceptionnel : écoles à 200m, tram à 100m, autoroute à 5 min. Copropriété bien entretenue avec jardin commun.`,
    features: {
      'Année de construction': '1985',
      'Chauffage': 'Radiateurs, mazout',
      'Parking': '1 place extérieure',
      'Cave': 'Oui',
      'Balcon': '6 m², vue place du Marché',
      'Vue': 'Place du Marché',
      'Ascenseur': 'Non',
      'État': 'Bon, cuisine rénovée 2022',
    },
    lat: 46.1830,
    lng: 6.1390,
    agent: {
      name: 'Gregory Lyonnet',
      agency: 'MEGGA Immobilier',
      phone: '+41 22 700 12 34',
      email: 'gregory@megga.ch',
      photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    },
  },
  {
    id: '7',
    title: 'Penthouse avec terrasse panoramique',
    price: 3200000,
    charges_monthly: 750,
    address: 'Quai du Mont-Blanc 18',
    city: 'Genève',
    canton: 'GE',
    postal_code: '1201',
    rooms: 6,
    bedrooms: 3,
    bathrooms: 2,
    surface_m2: 210,
    floor: 7,
    total_floors: 7,
    year_built: 2022,
    type: 'apartment',
    status: 'active',
    is_hot: true,
    photos: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop',
    ],
    description: `Penthouse d'exception au dernier étage d'une résidence prestigieuse sur le Quai du Mont-Blanc. Vue panoramique à 360° sur le lac Léman, le Mont-Blanc et la rade de Genève depuis une terrasse de 80 m².\n\nIntérieur signé par un architecte de renom : séjour de 55 m² triple exposition, cuisine Bulthaup, suite parentale avec jacuzzi et terrasse privée. Matériaux d'exception : marbre italien, boiseries en noyer, cuivre brossé.\n\nServices de la résidence : conciergerie 24h/24, spa avec piscine intérieure, salle de fitness, parking souterrain sécurisé. Adresse parmi les plus prestigieuses de Genève.`,
    features: {
      'Année de construction': '2022',
      'Chauffage': 'Sol, CAD (chauffage à distance)',
      'Parking': '2 places souterraines sécurisées',
      'Cave': 'Oui, 15 m²',
      'Terrasse': '80 m², panoramique',
      'Vue': 'Lac, Mont-Blanc, rade — 360°',
      'Ascenseur': 'Privatif',
      'État': 'Neuf, standing',
    },
    lat: 46.2085,
    lng: 6.1520,
    agent: {
      name: 'Gregory Lyonnet',
      agency: 'MEGGA Immobilier',
      phone: '+41 22 700 12 34',
      email: 'gregory@megga.ch',
      photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    },
  },
  {
    id: '8',
    title: 'Maison de ville rénovée',
    price: 1450000,
    charges_monthly: 0,
    address: 'Rue Ancienne 34',
    city: 'Carouge',
    canton: 'GE',
    postal_code: '1227',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    surface_m2: 160,
    floor: null,
    total_floors: null,
    year_built: 1890,
    type: 'house',
    status: 'active',
    photos: [
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
    ],
    description: `Maison de ville de caractère entièrement restaurée dans la vieille ville de Carouge, inscrite au patrimoine. Trois niveaux avec cour intérieure privée, alliant charme historique et confort moderne.\n\nRez-de-chaussée : entrée avec tomettes d'origine, séjour double avec cheminée en pierre, cuisine avec accès direct à la cour. Premier étage : deux chambres avec parquet ancien, salle de bains design. Deuxième étage : suite parentale mansardée avec poutres apparentes et salle d'eau.\n\nCour intérieure de 30 m² avec terrasse et plantation. Situation exceptionnelle en zone piétonne, au cœur de la vie carougeoise.`,
    features: {
      'Année de construction': '1890, restaurée 2021',
      'Chauffage': 'Sol (rez) + radiateurs (étages)',
      'Parking': 'Place louable à 100m',
      'Cave': 'Voûtée, d\'origine',
      'Cour': '30 m², aménagée',
      'Vue': 'Vieille ville de Carouge',
      'Patrimoine': 'Inscrite à l\'inventaire',
      'État': 'Restaurée avec soin',
    },
    lat: 46.1845,
    lng: 6.1420,
    agent: {
      name: 'Sophie Martin',
      agency: 'MEGGA Immobilier',
      phone: '+41 22 700 56 78',
      email: 'sophie@megga.ch',
      photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face',
    },
  },
]

/** Helper: get a listing by id */
export function getListingById(id: string): MockListing | undefined {
  return MOCK_LISTINGS.find((l) => l.id === id)
}

/** Convert MockListing to the lighter ListingCardData format */
export function toCardData(l: MockListing) {
  return {
    id: l.id,
    title: l.title,
    price: l.price,
    address: l.address,
    city: l.city,
    rooms: l.rooms,
    bedrooms: l.bedrooms,
    surface_m2: l.surface_m2,
    is_hot: l.is_hot,
    photos: l.photos,
  }
}
