// Curated Swiss cities/communes for the Localisation autocomplete.
// `name` matches the spelling used in market_listings.city where possible.
window.CH_CITIES = [
  { name: 'Genève', canton: 'GE' }, { name: 'Carouge', canton: 'GE' },
  { name: 'Meyrin', canton: 'GE' }, { name: 'Vernier', canton: 'GE' },
  { name: 'Lancy', canton: 'GE' }, { name: 'Lausanne', canton: 'VD' },
  { name: 'Montreux', canton: 'VD' }, { name: 'Nyon', canton: 'VD' },
  { name: 'Morges', canton: 'VD' }, { name: 'Vevey', canton: 'VD' },
  { name: 'Yverdon-les-Bains', canton: 'VD' }, { name: 'Renens', canton: 'VD' },
  { name: 'Zürich', canton: 'ZH' }, { name: 'Winterthur', canton: 'ZH' },
  { name: 'Uster', canton: 'ZH' }, { name: 'Dübendorf', canton: 'ZH' },
  { name: 'Bern', canton: 'BE' }, { name: 'Biel/Bienne', canton: 'BE' },
  { name: 'Thun', canton: 'BE' }, { name: 'Köniz', canton: 'BE' },
  { name: 'Basel', canton: 'BS' }, { name: 'Riehen', canton: 'BS' },
  { name: 'Lugano', canton: 'TI' }, { name: 'Bellinzona', canton: 'TI' },
  { name: 'Locarno', canton: 'TI' }, { name: 'Chiasso', canton: 'TI' },
  { name: 'Luzern', canton: 'LU' }, { name: 'St. Gallen', canton: 'SG' },
  { name: 'Rapperswil-Jona', canton: 'SG' }, { name: 'Fribourg', canton: 'FR' },
  { name: 'Bulle', canton: 'FR' }, { name: 'Neuchâtel', canton: 'NE' },
  { name: 'La Chaux-de-Fonds', canton: 'NE' }, { name: 'Sion', canton: 'VS' },
  { name: 'Sierre', canton: 'VS' }, { name: 'Martigny', canton: 'VS' },
  { name: 'Monthey', canton: 'VS' }, { name: 'Zug', canton: 'ZG' },
  { name: 'Aarau', canton: 'AG' }, { name: 'Baden', canton: 'AG' },
  { name: 'Wettingen', canton: 'AG' }, { name: 'Schaffhausen', canton: 'SH' },
  { name: 'Chur', canton: 'GR' }, { name: 'Davos', canton: 'GR' },
  { name: 'Frauenfeld', canton: 'TG' }, { name: 'Kreuzlingen', canton: 'TG' },
  { name: 'Solothurn', canton: 'SO' }, { name: 'Olten', canton: 'SO' },
  { name: 'Schwyz', canton: 'SZ' }, { name: 'Delémont', canton: 'JU' },
  { name: 'Liestal', canton: 'BL' }, { name: 'Herisau', canton: 'AR' },
  { name: 'Stans', canton: 'NW' }, { name: 'Sarnen', canton: 'OW' },
  { name: 'Altdorf', canton: 'UR' }, { name: 'Glarus', canton: 'GL' },
  { name: 'Appenzell', canton: 'AI' },
];
