-- Seed du corpus knowledge_snippets v1 (généré par scripts/knowledge-seed.mjs).
-- NE PAS ÉDITER À LA MAIN : éditer supabase/knowledge/corpus.seed.json puis régénérer.
-- Idempotent (ON CONFLICT slug). Un snippet actif a été relu en revue de PR.

INSERT INTO public.knowledge_snippets
  (slug, domain, canton, title, body_md, applies_to_actions, keywords, priority, source_url, source_ref, verified_at, review_after, status, lang)
VALUES
  ('ldtr-ge-autorisation-alienation-appartement-loue', 'ldtr_ge', 'GE', 'Quand la vente d''un appartement loué à Genève est-elle soumise à autorisation LDTR ?', $q$À Genève, l'aliénation d'un appartement d'habitation **jusqu'alors offert en location** est soumise à autorisation du département dès lors que le logement entre, par son loyer ou son type, dans une catégorie où sévit la pénurie (art. 39 al. 1 LDTR, rsGE L 5 20). La forme de la vente importe peu : cession en PPE, d'actions ou de parts sociales est visée de la même manière.

En pratique, il y a pénurie quand le taux de logements vacants de la catégorie concernée est inférieur à 2% du parc de même catégorie (art. 25 al. 2 LDTR). Compte tenu de la tension durable du logement à Genève, de nombreux appartements loués relèvent de catégories touchées par la pénurie ; il faut néanmoins vérifier la catégorie exacte au cas par cas.

Concrètement, avant d'annoncer à la vente un appartement actuellement loué, il faut vérifier si une autorisation d'aliéner est requise, car cela conditionne le calendrier et la faisabilité de la transaction. Chaque situation dépend de la catégorie du logement et des exceptions de l'art. 39 al. 4 : faire confirmer le cas concret par le notaire ou un juriste avant tout engagement.$q$, ARRAY['chat','suggest_next_action','draft_email']::text[], ARRAY['ldtr','l 5 20','autorisation d''aliener','alienation appartement loue','vente appartement loue geneve','penurie logement','art 39 ldtr','propriete par etages','ppe','vendre un bien loue','loi demolition transformation renovation']::text[], 9, 'https://silgeneve.ch/legis/data/rsg_l5_20.htm', 'LDTR/GE (rsGE L 5 20) art. 39 al. 1 ; art. 25 al. 2', '2026-07-05', '2027-01-05', 'active', 'fr'),
  ('ldtr-ge-motifs-refus-interet-public', 'ldtr_ge', 'GE', 'Pour quel motif le département genevois peut-il refuser l''autorisation d''aliéner un logement loué ?', $q$À Genève, le département **refuse** l'autorisation d'aliéner un appartement loué lorsqu'un motif prépondérant d'intérêt public ou d'intérêt général s'y oppose (art. 39 al. 2 LDTR, rsGE L 5 20). La loi précise elle-même où réside cet intérêt : dans le **maintien, en période de pénurie, de l'affectation locative** des appartements loués.

Autrement dit, la logique par défaut est protectrice du parc locatif : sortir un logement loué du marché de la location est présumé contraire à l'intérêt public tant que dure la pénurie. L'autorisation n'est accordée que si le cas relève d'une exception (art. 39 al. 4 : PPE dès construction, situation figée au 30 mars 1985, logement jamais loué, ou appartement ayant déjà fait l'objet d'une autorisation d'aliéner) ou de l'acquisition par le locataire en place.

Pour un dossier concret, l'appréciation de l'intérêt public relève du département et peut faire l'objet de recours : faire valider la stratégie par le notaire ou un juriste spécialisé avant de s'engager avec un acquéreur.$q$, ARRAY['chat','suggest_next_action']::text[], ARRAY['ldtr','refus autorisation','interet public','interet general','affectation locative','penurie logement','art 39 al 2 ldtr','maintien parc locatif','vente appartement loue geneve','l 5 20']::text[], 8, 'https://silgeneve.ch/legis/data/rsg_l5_20.htm', 'LDTR/GE (rsGE L 5 20) art. 39 al. 2 et al. 4', '2026-07-05', '2027-01-05', 'active', 'fr'),
  ('ldtr-ge-vente-au-locataire-en-place', 'ldtr_ge', 'GE', 'Le locataire en place peut-il acheter son appartement malgré la LDTR à Genève ?', $q$Oui, en principe, mais à des conditions strictes. À Genève, le désir d'un locataire **occupant effectivement son logement depuis 3 ans au moins** d'acquérir cet appartement n'est présumé l'emporter sur l'intérêt public que si des conditions sont réunies (art. 39 al. 3 LDTR, rsGE L 5 20).

La loi vise à empêcher le changement progressif d'affectation d'un immeuble locatif. Elle exige notamment que **60% des locataires en place acceptent formellement** l'acquisition ; dans ce cas, les locataires restants doivent recevoir la garantie de ne pas être contraints d'acheter leur appartement ni de partir.

Ce régime concerne les ventes individualisées au sein d'un immeuble locatif, pas seulement le locataire isolé. Le seuil des 60% et la durée d'occupation de 3 ans sont des conditions cumulatives avec le cadre général de l'art. 39. Comme il s'agit d'un cas sensible touchant plusieurs locataires, faire vérifier la faisabilité et le montage par le notaire ou un juriste avant toute promesse à l'acquéreur.$q$, ARRAY['chat','suggest_next_action','draft_email']::text[], ARRAY['ldtr','vente au locataire','locataire en place','acheter son appartement','3 ans occupation','60% des locataires','art 39 al 3 ldtr','changement d''affectation','immeuble locatif','l 5 20','vente appartement loue geneve']::text[], 8, 'https://silgeneve.ch/legis/data/rsg_l5_20.htm', 'LDTR/GE (rsGE L 5 20) art. 39 al. 3', '2026-07-05', '2027-01-05', 'active', 'fr'),
  ('ldtr-ge-travaux-transformation-renovation-soumis', 'ldtr_ge', 'GE', 'Quels travaux de rénovation ou transformation sont soumis à la LDTR à Genève ?', $q$À Genève, la LDTR (rsGE L 5 20) qualifie de **transformation** tous les travaux qui modifient l'architecture, le volume, l'implantation, la destination ou la distribution intérieure d'une maison d'habitation, créent de nouveaux logements (par ex. dans les combles), installent des équipements nouveaux d'une certaine importance (chauffage, eau chaude, ascenseur, salles de bains, cuisines), ou rénovent, c'est-à-dire remettent en état même partiellement un immeuble en améliorant le confort sans changer la distribution des logements (art. 3 al. 1).

À l'inverse, les **travaux courants d'entretien**, qui font partie des frais d'exploitation ordinaires de l'immeuble, ne sont pas assujettis à la loi (art. 3 al. 2).

Pour un bien à vendre, cette distinction compte : des travaux qualifiés de transformation peuvent nécessiter une autorisation et influencer le loyer admissible après travaux, donc le positionnement du bien. La frontière entre entretien et rénovation soumise est souvent débattue au cas par cas : faire trancher un projet concret par le département, le notaire ou un juriste avant de communiquer sur le potentiel de rénovation.$q$, ARRAY['chat','draft_description','analyze_market','suggest_next_action']::text[], ARRAY['ldtr','travaux soumis ldtr','transformation','renovation','travaux d''entretien','art 3 ldtr','distribution interieure','combles nouveaux logements','autorisation travaux geneve','l 5 20','loyer apres travaux']::text[], 7, 'https://silgeneve.ch/legis/data/rsg_l5_20.htm', 'LDTR/GE (rsGE L 5 20) art. 3 al. 1 et al. 2', '2026-07-05', '2027-01-05', 'active', 'fr'),
  ('bail-hausse-loyer-formule-officielle-co-269d', 'bail_co', NULL, 'Comment une hausse de loyer doit-elle etre notifiee au locataire ?', $q$En principe, une hausse de loyer n'est valable que si elle respecte trois conditions cumulatives de l'art. 269d CO.

1. **Formule officielle du canton.** L'avis de majoration doit etre notifie au moyen d'une formule agreee par le canton (jamais une simple lettre). La formule indique au locataire ses droits, notamment la maniere de contester.
2. **Motifs indiques.** La hausse doit etre motivee (par ex. adaptation du taux hypothecaire de reference, IPC, travaux a plus-value).
3. **Delai.** L'avis doit parvenir au locataire au moins dix jours avant le debut du delai de resiliation, pour le prochain terme de conge.

A defaut de formule officielle ou de motifs, la hausse est **nulle de plein droit** (art. 269d al. 2 CO). Le locataire peut la contester dans les 30 jours devant l'autorite de conciliation.

Pour un vendeur ou un bailleur que vous accompagnez, verifiez toujours que la formule cantonale correcte est utilisee. Pour un calcul de hausse contestable ou un cas litigieux, faites valider par un juriste ou l'office cantonal du logement avant l'envoi.$q$, ARRAY['chat','suggest_next_action','draft_email']::text[], ARRAY['hausse de loyer','augmentation de loyer','majoration de loyer','formule officielle','formule agreee par le canton','co 269d','article 269d','delai dix jours','notification hausse','nullite hausse loyer','motifs hausse loyer','avis de majoration']::text[], 8, 'https://www.consultationjuridiqueduvalentin.ch/post/diminution-et-augmentation-de-loyer', 'CO art. 269d al. 1 et al. 2', '2026-07-05', '2027-07-05', 'active', 'fr'),
  ('bail-contestation-loyer-initial-co-270', 'bail_co', NULL, 'Un nouveau locataire peut-il contester le loyer de depart ?', $q$Oui. L'art. 270 CO permet au locataire de contester le loyer initial s'il l'estime abusif, par exemple parce qu'il a ete contraint de conclure par necessite personnelle ou familiale ou en raison de la situation du marche, ou parce que le bailleur l'a sensiblement augmente par rapport au loyer precedent.

**Delai clef :** le locataire doit saisir l'autorite de conciliation dans les **30 jours qui suivent la reception de la chose** (remise des cles / entree dans les locaux). Passe ce delai, la contestation du loyer initial n'est en principe plus ouverte.

Cette voie vaut pour les logements comme pour les locaux commerciaux.

Pour un dossier concret ou un litige en cours, orientez le client vers l'autorite de conciliation cantonale ou un juriste : l'appreciation du caractere abusif est une question de fait qui depasse une simple information generale.$q$, ARRAY['chat','suggest_next_action']::text[], ARRAY['loyer initial','contestation loyer initial','loyer de depart','loyer abusif','co 270','article 270','delai 30 jours','autorite de conciliation','reception de la chose','changement de locataire','loyer precedent']::text[], 6, 'https://www.consultationjuridiqueduvalentin.ch/post/diminution-et-augmentation-de-loyer', 'CO art. 270 al. 1', '2026-07-05', '2027-07-05', 'draft', 'fr'),
  ('bail-conge-vente-protection-co-271-271a', 'bail_co', NULL, 'Peut-on resilier un bail pour vendre le bien, et le locataire peut-il l''annuler ?', $q$La resiliation reste possible, mais elle est encadree. L'art. 271 al. 1 CO interdit les conges contraires aux regles de la bonne foi : un tel conge est annulable.

L'art. 271a CO precise plusieurs cas d'annulabilite. En pratique, deux touchent directement une vente :

- **Conge-vente abusif** : le conge est annulable lorsqu'on peut se douter que le bailleur utilise l'argument de la resiliation pour contraindre le locataire a acheter le bien loue (art. 271a al. 1 let. c CO).
- **Conge pendant une procedure** : le conge donne en cours d'une procedure de conciliation ou judiciaire en rapport avec le bail est en principe annulable (art. 271a al. 1 let. d CO) ; en cas d'issue defavorable au bailleur, la resiliation ne peut en principe pas intervenir dans les trois ans suivant la fin du proces (art. 271a al. 1 let. e CO).

A noter : vendre un bien loue ne met pas fin au bail en soi. En regle generale, l'acquereur reprend le bail (le bail passe avec la chose). Un conge motive par un besoin propre et urgent de l'acquereur suit ses propres regles. Faites confirmer ce point au cas par cas.

Le locataire qui veut contester le conge doit saisir l'autorite de conciliation dans les 30 jours suivant sa reception (art. 273 al. 1 CO).

Avant de conseiller un vendeur sur un conge lie a une vente, faites valider la strategie par un juriste : l'annulabilite s'apprecie au cas par cas, et certains cantons peuvent en outre soumettre la vente de logements loues a autorisation. Verifiez le regime cantonal applicable.$q$, ARRAY['chat','suggest_next_action','analyze_market']::text[], ARRAY['conge','conge vente','resiliation en vue de vente','protection contre les conges','conge abusif','co 271','co 271a','article 271','article 271a','annulabilite du conge','bonne foi','vente bien loue','acquereur reprend le bail','delai 30 jours conge']::text[], 8, 'https://www.consultationjuridiqueduvalentin.ch/post/r%C3%A9siliation-et-prolongation-du-bail', 'CO art. 271 al. 1 et art. 271a al. 1', '2026-07-05', '2027-07-05', 'draft', 'fr'),
  ('bail-resiliation-ordinaire-delais-termes-co-266', 'bail_co', NULL, 'Quels delais et termes pour resilier ordinairement un bail ?', $q$Pour un bail d'habitation de duree indeterminee, la resiliation ordinaire suit les delais et termes du Code des obligations :

- **Habitation (art. 266c CO)** : preavis de trois mois, pour le terme convenu ou, a defaut, pour le terme fixe par l'usage local.

**Forme (art. 266l CO)** : le conge emanant du bailleur pour un logement doit etre notifie au moyen d'une formule officielle agreee par le canton, indiquant au locataire comment contester le conge ou demander une prolongation. Un conge du bailleur qui ne respecte pas cette forme est en principe nul. Le locataire, lui, n'a pas besoin de la formule officielle pour resilier (art. 266l al. 1 CO). Pour un logement familial, le conge doit etre notifie separement a chaque conjoint ou partenaire enregistre.

Le locataire dispose de 30 jours des la reception du conge pour saisir l'autorite de conciliation (art. 273 al. 1 CO) ; ce delai est imperatif et ne peut etre prolonge.

Les termes usuels locaux varient d'un canton a l'autre : verifiez le terme applicable et le modele de formule cantonal. Les locaux commerciaux obeissent a des delais distincts : faites valider ce point, ainsi que tout conge sensible, par un juriste avant l'envoi.$q$, ARRAY['chat','suggest_next_action','draft_email']::text[], ARRAY['resiliation ordinaire','resiliation bail','delai de conge','terme usuel local','preavis 3 mois','preavis 6 mois','co 266c','co 266d','co 266l','article 266','formule officielle conge','conge bailleur','logement familial conge','co 273','delai contestation conge']::text[], 7, 'https://suissedroit.ch/fr/droit-du-bail/resiliation-de-bail-droits-locataire', 'CO art. 266c, 266d, 266l al. 2, 273 al. 1', '2026-07-05', '2027-07-05', 'draft', 'fr'),
  ('lex-koller-personne-etranger-assujettissement', 'lex_koller', NULL, 'Qui est « personne à l''étranger » et quel achat est soumis à la Lex Koller ?', $q$Selon la LFAIE (Lex Koller), l'acquisition d'un immeuble est soumise à autorisation quand **trois conditions cumulatives** sont réunies : l'acquéreur est une personne à l'étranger, l'immeuble est assujetti selon son affectation, et le droit acquis vaut acquisition d'immeuble.

En principe, sont « personnes à l'étranger » : les étrangers domiciliés à l'étranger ; les étrangers domiciliés en Suisse qui ne sont ni ressortissants UE/AELE ni titulaires d'un permis C valable ; les sociétés ayant leur siège à l'étranger ou dominées par des personnes à l'étranger (présomption dès que celles-ci détiennent plus d'un tiers du capital ou des droits de vote). Sont hors champ : les Suisses, les ressortissants UE/AELE avec domicile légal et effectif en Suisse, et les titulaires d'un permis C effectivement domiciliés.

Le domicile effectif se prouve (art. 23 ss CC) : une simple autorisation de séjour ne suffit pas. La cause de l'acquisition (achat, donation, héritage) est en principe indifférente. Cas concret sensible : faire trancher l'assujettissement par l'autorité cantonale compétente et le notaire.$q$, ARRAY['chat','analyze_kyc','suggest_next_action']::text[], ARRAY['lex koller','lfaie','personne a l''etranger','personne a letranger','acquisition immeuble etranger','permis c','ue aele','domicile effectif','autorisation acquisition','assujettissement','achat etranger suisse','societe domination etrangere']::text[], 9, 'https://www.bj.admin.ch/dam/bj/fr/data/wirtschaft/grundstueckerwerb/lex-f.pdf', 'LFAIE (Lex Koller) art. 2, 5, 6 — Aide-mémoire OFJ, ch. 4-5', '2026-07-05', '2027-07-05', 'active', 'fr'),
  ('lex-koller-residence-principale-secondaire-commercial', 'lex_koller', NULL, 'Lex Koller : résidence principale, secondaire ou immeuble commercial — libre ou soumis ?', $q$La LFAIE distingue selon l'**affectation** de l'immeuble.

- **Résidence principale** : un étranger avec domicile en Suisse peut acquérir librement, sans autorisation, un logement au lieu de son domicile effectif (art. 2 al. 2 let. b LFAIE). Il doit l'habiter personnellement et ne pas le louer, même partiellement ; l'achat se fait en nom propre. Au-delà de 3'000 m² de parcelle, le registre foncier renvoie à l'autorité (risque de pur placement de capitaux).
- **Immeuble d'établissement stable / commercial** (fabrique, bureau, magasin, hôtel, cabinet médical) : acquisition libre, sans autorisation, y compris comme placement (art. 2 al. 2 let. a LFAIE). Mais créer ou louer des **logements** n'est pas une activité économique et redevient soumis.
- **Résidence secondaire** : en principe soumise à autorisation. Exception non assujettie pour le frontalier UE/AELE (permis G) dans sa région de travail, qui doit l'occuper lui-même (art. 7 let. j LFAIE).

Règle sensible : faire qualifier l'affectation par le notaire avant tout engagement.$q$, ARRAY['chat','analyze_kyc','suggest_next_action','draft_description']::text[], ARRAY['residence principale','residence secondaire','immeuble commercial','etablissement stable','logement de vacances','lex koller','lfaie','frontalier permis g','acquisition libre','placement de capitaux','sans autorisation','domicile effectif suisse']::text[], 8, 'https://www.bj.admin.ch/dam/bj/fr/data/wirtschaft/grundstueckerwerb/lex-f.pdf', 'LFAIE (Lex Koller) art. 2 al. 2, art. 7 let. j — Aide-mémoire OFJ, ch. 6', '2026-07-05', '2027-07-05', 'draft', 'fr'),
  ('lex-koller-sanctions-nullite-contournement', 'lex_koller', NULL, 'Lex Koller : que risque-t-on si on achète sans autorisation ou en contournant la loi ?', $q$Un acte soumis à autorisation reste **inefficace** tant que l'autorisation n'est pas en force (art. 26 al. 1 LFAIE) : les parties restent liées, mais l'acte est frappé de **nullité** en cas de refus, de révocation, ou de rejet de l'inscription au registre foncier. Il y a aussi nullité si l'acquéreur exécute l'acte (p. ex. transfert d'actions d'une société immobilière) sans solliciter l'autorisation (art. 26 al. 2 LFAIE).

En cas de nullité, les prestations fournies se répètent dans le délai d'un an (art. 26 al. 4) ; à défaut, l'autorité cantonale ou l'Office fédéral de la justice peut demander le rétablissement de l'état antérieur ou la **liquidation forcée** de l'immeuble (art. 27 LFAIE).

Les actes visant à **éluder** le régime, les fausses indications et l'inobservation des charges sont des infractions pénales (peine privative de liberté, peine pécuniaire ou amende, art. 28-31 LFAIE). Sur un montage suspect, orienter vers le notaire et un juriste.$q$, ARRAY['chat','analyze_kyc','suggest_next_action']::text[], ARRAY['nullite','sanctions lex koller','contournement','eluder autorisation','acte inefficace','liquidation forcee','lfaie','lex koller','revocation autorisation','infraction penale','achat sans autorisation','societe immobiliere transfert actions']::text[], 8, 'https://www.bj.admin.ch/dam/bj/fr/data/wirtschaft/grundstueckerwerb/lex-f.pdf', 'LFAIE (Lex Koller) art. 26, 27, 28-31 — Aide-mémoire OFJ, ch. 11', '2026-07-05', '2027-07-05', 'draft', 'fr'),
  ('financement-fonds-propres-minimum-20-dont-10-durs', 'financement', NULL, 'Combien de fonds propres faut-il pour acheter, et le 2e pilier compte-t-il ?', $q$En principe, pour un logement en propriété à usage propre, une banque finance en général au maximum 80 % de la valeur de nantissement selon sa politique de crédit : l'acheteur apporte donc au moins **20 % de fonds propres**.

Point clé souvent mal compris, et directement fixé par l'ASB : sur ces fonds propres, une **part minimale de 10 % de la valeur de nantissement ne peut PAS provenir du 2e pilier** (versement anticipé ou mise en gage LPP). Ce sont les fonds propres dits « durs » : épargne, pilier 3a, donation, avancement d'hoirie, titres, valeur de rachat d'assurance. Le 2e pilier peut couvrir le solde des fonds propres.

Cette règle des 10 % « durs » est un standard d'auto-régulation de l'ASB, reconnu par la FINMA comme standard prudentiel minimum. Chaque banque peut être plus stricte selon sa politique de risque.

Le calcul exact de la valeur de nantissement (souvent inférieure au prix d'achat) et l'admissibilité d'une donation relèvent du dossier bancaire et, pour les aspects contractuels, du notaire. À confirmer au cas par cas avec la banque prêteuse.$q$, ARRAY['chat','suggest_next_action','analyze_market']::text[], ARRAY['fonds propres','fonds propres durs','20 pourcent','10 pourcent','2e pilier','deuxieme pilier','lpp','valeur de nantissement','versement anticipe','mise en gage','pilier 3a','apport minimum','financement hypothecaire','fond propre','fonds propre minimum','hypotheque']::text[], 9, 'https://www.swissbanking.ch/_Resources/Persistent/9/5/c/9/95c9c3cbf40cb4ad6a10be39d257713f1c169c6d/SBA_Directives_relatives_aux_exigenes_minimales_pour_les_financements_hypoth%C3%A9caires_FR.pdf', 'ASB, Directives relatives aux exigences minimales pour les financements hypothécaires (août 2019), ch. 3.1 « Fonds propres » — reconnues par la FINMA (circ. FINMA 2008/10)', '2026-07-05', '2027-07-05', 'active', 'fr'),
  ('financement-tenue-des-charges-un-tiers-taux-theorique', 'financement', NULL, 'Comment la banque calcule si l''acheteur peut « tenir » l''hypothèque ?', $q$Au-delà des fonds propres, la banque vérifie la **tenue des charges** (capacité financière). En pratique courante suisse, les coûts de logement ne doivent en principe **pas dépasser environ un tiers (33 %) du revenu brut régulier**.

Ces coûts sont calculés avec un **taux d'intérêt théorique (calculatoire) d'environ 4,5 à 5 %**, et non le taux du marché du moment : c'est un test de résistance à une remontée des taux. On y ajoute les **frais d'entretien (env. 0,7 à 1 % de la valeur du bien)** et l'**amortissement** de la 2e hypothèque.

Attention : contrairement au 20 % / 10 % de fonds propres, ce seuil du tiers et le taux de 5 % ne sont pas fixés par les directives minimales de l'ASB ; ce sont des conventions de calcul propres à chaque banque, qui peuvent varier légèrement d'un établissement à l'autre.

Le résultat dépend fortement du dossier (revenus, autres crédits). À faire chiffrer par la banque, et à valider avec un conseiller financier pour les situations complexes.$q$, ARRAY['chat','suggest_next_action','analyze_market']::text[], ARRAY['taux d''effort','tenue des charges','capacite financiere','un tiers','33 pourcent','taux theorique','taux calculatoire','5 pourcent','taux fictif','frais d''entretien','amortissement','revenu brut','charges hypothecaires','supportabilite','taux d''endettement']::text[], 9, 'https://www.vermoegenszentrum.ch/fr/competences/un-bien-foncier-doit-etre-financierement-supportable', 'VZ VermögensZentrum, « Un bien foncier doit être financièrement supportable » (pratique bancaire suisse) ; seuil du tiers confirmé par Raiffeisen, « Capacité financière d''une hypothèque »', '2026-07-05', '2026-10-05', 'active', 'fr'),
  ('financement-amortissement-obligatoire-deux-tiers-15-ans', 'financement', NULL, 'L''hypothèque doit-elle être remboursée, et dans quel délai ?', $q$Oui, en partie. Pour un logement en propriété à usage propre, la dette hypothécaire doit être **ramenée aux deux tiers (2/3) de la valeur de nantissement** de l'immeuble en **15 ans au maximum**.

L'amortissement doit être **linéaire** et commencer au plus tard **douze mois après le versement** (fin de trimestre). Il peut être **direct** (remboursement à la banque) ou **indirect** (apport et nantissement d'un pilier 3a, d'une assurance-vie ou d'autres bankable assets) ; l'amortissement indirect commence au plus tard à la fin de l'année suivant le versement.

Dans la pratique bancaire courante (hors des Directives ASB citées ici), le financement est souvent structuré en une 1re hypothèque, en principe non amortissable, et une 2e hypothèque correspondant à la part de dette à ramener aux deux tiers, c'est cette part qui fait l'objet de l'amortissement obligatoire sur 15 ans. Les modalités exactes (montant, horizon, âge) relèvent de la politique de chaque banque et sont à confirmer avec elle.

C'est une règle d'auto-régulation ASB reconnue par la FINMA comme standard minimum. Le choix direct/indirect a des effets fiscaux (déduction des intérêts, valeur locative) : à valider avec la banque et, pour l'optimisation fiscale, un conseiller ou le notaire.$q$, ARRAY['chat','suggest_next_action']::text[], ARRAY['amortissement','amortissement obligatoire','deux tiers','2/3','15 ans','premiere hypotheque','deuxieme hypotheque','seconde hypotheque','amortissement direct','amortissement indirect','valeur de nantissement','remboursement hypotheque','pilier 3a','amortir','amortisation']::text[], 8, 'https://www.swissbanking.ch/_Resources/Persistent/9/5/c/9/95c9c3cbf40cb4ad6a10be39d257713f1c169c6d/SBA_Directives_relatives_aux_exigenes_minimales_pour_les_financements_hypoth%C3%A9caires_FR.pdf', 'ASB, Directives relatives aux exigences minimales pour les financements hypothécaires (août 2019), ch. 3.2 « Amortissement » — reconnues par la FINMA (circ. FINMA 2008/10)', '2026-07-05', '2027-07-05', 'active', 'fr'),
  ('notaire-role-vente-immobiliere-ge', 'notarial', 'GE', 'Quel est le rôle du notaire dans une vente immobilière à Genève ?', $q$En droit suisse, une vente d'immeuble n'est valable que si elle est passée devant notaire, en la **forme authentique** (art. 216 al. 1 CO : « Les ventes d'immeubles ne sont valables que si elles sont faites par acte authentique »). Un simple accord sous seing privé ne suffit pas.

La séquence usuelle à Genève :
1. **Avant-contrat / promesse de vente** : le notaire peut rédiger un acte engageant les deux parties, souvent sous conditions suspensives (par ex. financement). La promesse de vente doit elle aussi revêtir la forme authentique (art. 216 al. 2 CO).
2. **Acte de vente authentique** : après vérifications, le notaire rédige et fait signer l'acte, qui scelle juridiquement la transaction.
3. **Inscription au Registre foncier** cantonal : étape indispensable pour rendre le transfert opposable aux tiers ; le notaire s'en charge.

Le notaire est un officier public impartial. Pour un dossier concret (conditions, délais, clauses), la rédaction et la validation relèvent du notaire instrumentant.$q$, ARRAY['chat','suggest_next_action','draft_email']::text[], ARRAY['notaire','acte authentique','forme authentique','vente immobiliere','art 216 co','co 216','promesse de vente','avant-contrat','compromis','inscription registre foncier','role du notaire','geneve','vente immeuble']::text[], 9, 'https://www.droit-bilingue.ch/fr-en/2/22/220-216-230.html', 'CO art. 216 al. 1 et 2 (droit fédéral) ; séquence : Chambre des notaires de Genève', '2026-07-05', '2027-07-05', 'active', 'fr'),
  ('droits-enregistrement-vente-immobiliere-ge-3pct', 'droits_enregistrement_ge', 'GE', 'Quel est le taux des droits d''enregistrement (droits de mutation) sur une vente immobilière à Genève ?', $q$À Genève, le transfert de propriété immobilière à titre onéreux est soumis à un **droit d'enregistrement de 3 %** du prix (art. 33 de la loi sur les droits d'enregistrement, LDE / rsGE D 3 30). Ces droits sont couramment appelés « droits de mutation ».

La loi vise « tous les actes translatifs à titre onéreux de la propriété, de la nue-propriété ou de l'usufruit de biens immobiliers sis dans le canton de Genève », sous réserve des exceptions prévues par la LDE. Le taux de 3 % s'applique donc à l'acte d'achat lui-même ; un acte hypothécaire (cédule) suit un régime distinct.

Des allègements existent pour la résidence principale (dispositif Casatax), sous conditions et plafonds. Comme les barèmes et exonérations évoluent et dépendent de la situation exacte (nature du bien, qualité de l'acquéreur), toute application chiffrée à un dossier concret doit être confirmée par le notaire instrumentant.$q$, ARRAY['chat','analyze_market','suggest_next_action']::text[], ARRAY['droits d''enregistrement','droits de mutation','droit de mutation','taux 3%','lde','rsge d 3 30','vente immobiliere','transfert propriete','geneve','casatax','frais achat','impot mutation','droit enregistrement']::text[], 9, 'https://silgeneve.ch/legis/data/rsg_d3_30.htm', 'LDE/GE art. 33 (rsGE D 3 30, Loi sur les droits d''enregistrement)', '2026-07-05', '2026-10-05', 'active', 'fr'),
  ('emoluments-notaire-registre-foncier-ge', 'notarial', 'GE', 'À combien s''élèvent les émoluments du notaire et l''inscription au Registre foncier à Genève ?', $q$Ce qu'on appelle « frais de notaire » à Genève regroupe plusieurs postes, pas seulement la rémunération du notaire. Selon la Chambre des notaires de Genève, un **acte d'achat** se décompose ainsi (ordres de grandeur, en pourcentage du prix) :
- **3 %** de droits d'enregistrement (droits de mutation) ;
- **0,3 %** au titre de l'inscription au Registre foncier ;
- **environ 0,7 %** perçus par le notaire pour la rémunération de son travail (émoluments).

Le total avoisine donc **~4 %** du prix du bien. Les émoluments du notaire sont fixés par le règlement cantonal (REmNoT) et ceux du Registre foncier par le règlement applicable (REmRFMO) ; ils ne sont donc pas librement négociables.

Un acte hypothécaire suit un barème séparé (droits d'enregistrement d'environ 1,365 % de la cédule). Ces pourcentages sont indicatifs : le décompte exact, avec débours, est établi par l'étude notariale.$q$, ARRAY['chat','analyze_market','suggest_next_action']::text[], ARRAY['emoluments notaire','frais de notaire','inscription registre foncier','emoluments registre foncier','remnot','remrfmo','4 pourcent','0.3%','0.7%','geneve','cout acte achat','debours','frais achat immobilier']::text[], 8, 'https://notaires-geneve.ch/fr/activites-immobilier-lappellation-frais-de-notaire-est-tromp', 'Chambre des notaires de Genève, « L''appellation frais de notaire est trompeuse » ; barèmes : REmNoT et REmRFMO', '2026-07-05', '2026-10-05', 'active', 'fr'),
  ('qui-paie-frais-notaire-vente-ge', 'notarial', 'GE', 'Qui paie les frais de notaire lors d''une vente immobilière à Genève : acheteur ou vendeur ?', $q$À Genève, ce que l'on appelle couramment les « frais de notaire » ne correspond pas à la rémunération du notaire : selon la Chambre des notaires de Genève, ces frais « englobent l'ensemble des frais dus en raison de la transaction, impôt étatique et inscription au Registre foncier compris ». L'émolument propre du notaire n'en représente qu'une part.\n\nLe notaire joue le rôle d'intermédiaire fiscal : la Chambre précise qu'il « est personnellement responsable du paiement des droits d'enregistrement et d'inscription au Registre foncier ». C'est pourquoi il encaisse ces montants, puis les verse directement et en totalité à l'État (droits d'enregistrement) et au Registre foncier (émolument d'inscription).\n\nDans la pratique genevoise, ces frais sont généralement mis à la charge de l'acquéreur, mais la répartition entre les parties peut être aménagée par convention : toute clause dérogatoire doit être vérifiée et formalisée par le notaire, qui reste la référence pour la répartition applicable à un dossier donné. (Note : la question de qui paie l'impôt sur les bénéfices et gains immobiliers relève du droit fiscal cantonal et n'est pas traitée par la source citée ; à documenter séparément.)$q$, ARRAY['chat','suggest_next_action','draft_email']::text[], ARRAY['qui paie frais notaire','repartition frais','acheteur paie','acquereur','vendeur','frais de notaire','droits d''enregistrement','registre foncier','geneve','charge des frais','impot gain immobilier','cout vente']::text[], 8, 'https://notaires-geneve.ch/fr/activites-immobilier-lappellation-frais-de-notaire-est-tromp', 'Chambre des notaires de Genève, « L''appellation frais de notaire est trompeuse »', '2026-07-05', '2026-10-05', 'draft', 'fr'),
  ('ge-ibgi-gain-immobilier-degressivite-duree', 'fiscalite', 'GE', 'Comment est imposée la plus-value lors de la vente d''un bien à Genève (IBGI) ?', $q$À Genève, la vente d'un bien immobilier déclenche en principe l'**impôt sur les bénéfices et gains immobiliers (IBGI)**. Il porte sur le bénéfice, soit la différence entre la valeur d'aliénation (prix de vente, moins une éventuelle commission de courtage) et la valeur d'acquisition (prix d'achat, plus les travaux à plus-value réalisés).

Le taux est **dégressif selon la durée de détention** : plus le bien est conservé longtemps, plus le taux baisse. Barème officiel : moins de 2 ans 50 %, dès 2 ans 40 %, dès 4 ans 30 %, dès 6 ans 20 %, dès 8 ans 15 %, dès 10 ans 10 %, dès 25 ans 2 % (depuis le 1er janvier 2025).

Ce mécanisme vise à décourager la spéculation à court terme. Le calcul exact (travaux déductibles, dates retenues) dépend du dossier : pour un chiffrage engageant, renvoyer le client à l'AFC-GE ou à son notaire.$q$, ARRAY['chat','analyze_market','suggest_next_action']::text[], ARRAY['ibgi','impot gains immobiliers','impot benefices immobiliers','plus-value immobiliere','gain immobilier','duree de detention','taux degressif','degressivite','valeur alienation','valeur acquisition','impot vente bien geneve','ibgf','impot benefice gain immobilier']::text[], 8, 'https://www.ge.ch/impot-benefices-gains-immobiliers/calculer-montant-impot', 'AFC-GE — IBGI, barème selon la durée de détention (LCP/GE)', '2026-07-05', '2027-01-05', 'active', 'fr'),
  ('ge-remploi-report-imposition-gain-immobilier', 'fiscalite', 'GE', 'Le client peut-il éviter l''impôt sur le gain en rachetant un logement (remploi) ?', $q$Oui, en principe, via le **remploi**. Lorsqu'un propriétaire vend son **domicile principal** à Genève et réinvestit le produit dans l'achat d'un logement de remplacement, l'IBGI correspondant à la somme réinvestie peut être **différé**.

Conditions clés selon l'AFC-GE : le bien de remplacement doit se trouver **en Suisse** et être occupé par l'acquéreur au titre de **domicile principal** ; le réinvestissement doit intervenir dans un **délai de 5 ans maximum**.

Point essentiel à expliquer au client : le remploi n'est **pas une exonération**, seulement un report. L'impôt différé redeviendra dû lors d'une vente ultérieure sans remploi ou si le bien cesse de servir de domicile principal. Pour valider l'éligibilité d'un cas concret, les conditions précises et les montants, renvoyer au notaire ou à l'AFC-GE.$q$, ARRAY['chat','suggest_next_action','draft_email']::text[], ARRAY['remploi','report imposition','impot differe','logement de remplacement','residence principale','domicile principal','rachat logement','reinvestissement','differer impot gain immobilier','ibgi remploi','reemploi','remplois']::text[], 7, 'https://www.ge.ch/impot-benefices-gains-immobiliers/beneficier-du-remploi', 'AFC-GE — Bénéficier du remploi (IBGI)', '2026-07-05', '2027-01-05', 'draft', 'fr'),
  ('ch-valeur-locative-principe-abolition-votation-2025', 'fiscalite', NULL, 'C''est quoi la valeur locative, et est-elle vraiment supprimée ?', $q$La **valeur locative** est un revenu fictif : selon le droit fédéral, quiconque possède un immeuble et l'occupe personnellement doit déclarer une valeur locative comme **revenu imposable**, comme s'il se louait son propre logement. En contrepartie, le propriétaire occupant peut en principe déduire ses intérêts hypothécaires et certains frais d'entretien.

Ce système est en cours de changement. Le 28 septembre 2025, le peuple a accepté (57,7 % des voix) la **réforme de l'imposition de la propriété du logement**, qui abolit l'imposition de la valeur locative des résidences principales et secondaires et limite les déductions correspondantes.

Attention pour le conseil client : la réforme est votée mais **pas encore en vigueur**. La page officielle indique que le Conseil fédéral fixera la date d'entrée en vigueur après consultation des cantons (les commentaires de presse évoquent un horizon 2028-2029, non confirmé ici). Jusqu'à cette entrée en vigueur, la valeur locative reste imposable. Pour toute situation concrète, renvoyer au notaire ou à l'administration fiscale.$q$, ARRAY['chat','analyze_market','suggest_next_action']::text[], ARRAY['valeur locative','revenu fictif','propietaire occupant','proprietaire occupant','abolition valeur locative','suppression valeur locative','votation valeur locative','reforme imposition propriete logement','interets hypothecaires deduction','residence secondaire impot','valeur locative imposable','valeur locatif']::text[], 9, 'https://www.efd.admin.ch/fr/votation-reforme-imposition-propriete-logement', 'DFF/AFC — Réforme de l''imposition de la propriété du logement (votation 28.09.2025)', '2026-07-05', '2027-01-05', 'active', 'fr'),
  ('cecb-definition-classes-argument-vente', 'cecb', NULL, 'C''est quoi le CECB et à quoi servent les classes A à G ?', $q$Le **CECB** (Certificat énergétique cantonal des bâtiments) est un certificat identique dans toute la Suisse qui, selon l'organisme officiel, « évalue la qualité de l'enveloppe et le bilan énergétique global d'un bâtiment, ainsi que ses émissions directes de CO2 ».

Il classe le bâtiment sur **sept niveaux, de A (très performant, isolation excellente + renouvelables) à G (ancien, sans isolation suffisante)**. La note reflète trois axes : efficacité de l'enveloppe, efficacité énergétique globale, émissions directes de CO2. Le **CECB Plus** ajoute au certificat un rapport de conseil en vue d'une rénovation.

À la vente, une bonne classe (A/B/C) est un argument concret : charges de chauffage plus basses, pas de gros travaux à prévoir. Une classe faible (F/G) signale au contraire un potentiel de rénovation à chiffrer. Présentez le CECB comme une information de transparence, pas comme une garantie de valeur. Pour l'obligation exacte selon le canton et le type de bien, renvoyez au service cantonal de l'énergie compétent.$q$, ARRAY['chat','draft_description','suggest_next_action']::text[], ARRAY['cecb','certificat energetique','certificat energetique cantonal des batiments','classe energetique','classe a g','cecb plus','performance energetique','etiquette energie','idc','renovation energetique','cecb geneve','bilan energetique']::text[], 7, 'https://www.cecb.ch/le-cecb/quest-ce-que-le-cecb/', 'CECB — cecb.ch, page « Qu''est-ce que le CECB »', '2026-07-05', '2027-07-05', 'active', 'fr'),
  ('cecb-obligatoire-vente-geneve', 'cecb', 'GE', 'Le CECB est-il obligatoire pour vendre à Genève ?', $q$Attention à une idée reçue fréquente : **à Genève, le CECB n'est en principe PAS obligatoire lors de la vente** d'un bien. Une source spécialisée genevoise le formule ainsi : « vous n'êtes pas dans l'obligation de réaliser un CECB® lors de la vente d'une maison ». Genève n'a pas repris l'obligation de CECB à la vente que connaissent certains autres cantons (p. ex. Vaud, Fribourg).

Le CECB (ou CECB Plus) devient toutefois **requis dans des cas précis**, notamment pour toucher certaines subventions cantonales de rénovation énergétique. Par ailleurs, à Genève, les propriétaires de bâtiments chauffés avec au moins 5 preneurs de chaleur doivent calculer un indice de dépense de chaleur (IDC), qui est une obligation distincte du CECB.

Le CECB reste un argument de vente utile même sans obligation. Comme les conditions et les seuils de subvention évoluent, faites confirmer le cas concret par l'office cantonal de l'énergie (OCEN) ou un expert CECB agréé avant d'affirmer une obligation au vendeur.$q$, ARRAY['chat','suggest_next_action','draft_email']::text[], ARRAY['cecb obligatoire','cecb geneve','cecb vente','certificat energetique obligatoire','ocen','idc','indice depense chaleur','subvention renovation','obligation vente geneve','cecb plus','energie geneve']::text[], 8, 'https://www.i-neea.ch/en/news/certificat-cecb-geneve-que-dit-la-reglementation-du-canton', 'i-neea.ch — « Certificat CECB Genève : que dit la réglementation du canton »', '2026-07-05', '2027-01-05', 'draft', 'fr'),
  ('lba-courtier-immobilier-champ-application', 'lab_lba', NULL, 'Un courtier immobilier est-il soumis à la LBA (anti-blanchiment) ?', $q$En l'état du droit fédéral, **le simple courtage / négoce immobilier n'est en principe pas un « intermédiaire financier » soumis à la LBA** : l'assujettissement vise avant tout ceux qui gèrent des valeurs patrimoniales ou des flux financiers pour autrui. Une transaction immobilière suisse passe par un **notaire** (acte authentique obligatoire) et par une banque pour les fonds, deux acteurs eux déjà soumis à des obligations de diligence.

À noter : une **révision de la LBA étend le champ d'application** à certaines activités de conseil. Le Secrétariat d'État aux questions financières internationales (SIF/DFF) écrit que « certaines activités de conseil, par exemple dans le cadre de transactions immobilières […], seront désormais soumises à la LBA ». Cette extension **entre en vigueur le 1er octobre 2026** et vise le conseil, pas nécessairement tout courtage.

Ce point est sensible et évolutif. Ne concluez pas seul à un (non-)assujettissement : faites qualifier la situation par un juriste ou l'organisme d'autorégulation compétent avant d'affirmer quoi que ce soit à un client.$q$, ARRAY['chat','analyze_kyc','suggest_next_action']::text[], ARRAY['lba','blanchiment','anti blanchiment','courtier immobilier lba','intermediaire financier','loi blanchiment argent','gafi','revision lba 2026','activite de conseil','conseil transaction immobiliere','assujettissement lba','aml']::text[], 8, 'https://www.sif.admin.ch/fr/loi-sur-le-blanchiment-dargent', 'SIF / DFF — admin.ch, « Lutte contre le blanchiment d''argent » (révision LBA)', '2026-07-05', '2027-01-05', 'draft', 'fr'),
  ('kyc-megga-facultatif-notaire-finalise', 'notarial', NULL, 'Le KYC de MEGGA est-il obligatoire pour vendre ? Bloque-t-il la vente ?', $q$Non. En Suisse, **une vente immobilière n'est valable que par un acte authentique établi par un notaire** ; comme le rappelle une source de référence, « la vente d'un bien immobilier n'est valable que si elle fait l'objet d'un acte authentique établi par un notaire ». C'est le notaire, tiers neutre, qui vérifie l'identité des parties (passeport / carte d'identité), s'assure de leur capacité et procède à l'inscription au registre foncier. Les vérifications légales de la transaction reposent donc sur lui.

Le **KYC proposé dans MEGGA est un outil d'assistance facultatif** : il aide à préparer et documenter un dossier client en amont, mais il **ne remplace pas le notaire et ne bloque aucune étape de la vente**. Un dossier KYC incomplet ou non lancé n'empêche ni une visite, ni une offre, ni la signature chez le notaire.

Présentez toujours le KYC comme une aide, jamais comme une condition légale. Pour toute exigence d'identification ou de diligence propre à un dossier, la référence reste le notaire instrumentant (ou un juriste).$q$, ARRAY['chat','analyze_kyc','suggest_next_action','draft_email']::text[], ARRAY['kyc','kyc facultatif','kyc obligatoire','know your customer','notaire','acte authentique','identification client','diligence','vente bloquee','registre foncier','verification identite','kyc megga','bloquant']::text[], 9, 'https://immo.raiffeisen.ch/fr/wissen/lexikon/notaire/', 'Raiffeisen — lexique immobilier, « Notaire »', '2026-07-05', '2027-07-05', 'active', 'fr')
ON CONFLICT (slug) DO UPDATE SET
  domain = EXCLUDED.domain, canton = EXCLUDED.canton, title = EXCLUDED.title,
  body_md = EXCLUDED.body_md, applies_to_actions = EXCLUDED.applies_to_actions,
  keywords = EXCLUDED.keywords, priority = EXCLUDED.priority,
  source_url = EXCLUDED.source_url, source_ref = EXCLUDED.source_ref,
  verified_at = EXCLUDED.verified_at, review_after = EXCLUDED.review_after,
  status = EXCLUDED.status, lang = EXCLUDED.lang, updated_at = now();
